#!/bin/sh
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:/var/lib/flatpak/exports/share:$HOME/.local/share/flatpak/exports/share"
dmenu_path_desktop | dmenu "$@" | xargs gtk-launch &
